// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJpwkeeeuKRJ9y3TUhnDZjIHYkbW6j2uU',
    appId: '1:285696136744:web:30689da1fcc0158004c71d',
    messagingSenderId: '285696136744',
    projectId: 'balloonman-68a8b',
    authDomain: 'balloonman-68a8b.firebaseapp.com',
    storageBucket: 'balloonman-68a8b.firebasestorage.app',
    measurementId: 'G-ZG3J25F296',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvHV6ujyVounKi9MSNeGsyqrXpSFRXygY',
    appId: '1:285696136744:android:44231e79d7ae508004c71d',
    messagingSenderId: '285696136744',
    projectId: 'balloonman-68a8b',
    storageBucket: 'balloonman-68a8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsuo6vWlETIC7zcZ2DgtmK7xwZk_IqKsc',
    appId: '1:285696136744:ios:22f8356c969ad5d604c71d',
    messagingSenderId: '285696136744',
    projectId: 'balloonman-68a8b',
    storageBucket: 'balloonman-68a8b.firebasestorage.app',
    iosBundleId: 'com.example.balloonman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsuo6vWlETIC7zcZ2DgtmK7xwZk_IqKsc',
    appId: '1:285696136744:ios:22f8356c969ad5d604c71d',
    messagingSenderId: '285696136744',
    projectId: 'balloonman-68a8b',
    storageBucket: 'balloonman-68a8b.firebasestorage.app',
    iosBundleId: 'com.example.balloonman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJpwkeeeuKRJ9y3TUhnDZjIHYkbW6j2uU',
    appId: '1:285696136744:web:fc6c04270cce598204c71d',
    messagingSenderId: '285696136744',
    projectId: 'balloonman-68a8b',
    authDomain: 'balloonman-68a8b.firebaseapp.com',
    storageBucket: 'balloonman-68a8b.firebasestorage.app',
    measurementId: 'G-GTFLLJRBKN',
  );
}
